export const ActionTypes = {
  SET_CATEGORY: 'SET_CATEGORY',
  ADD_CATEGORY: 'ADD_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  SET_TYPE: "SET_TYPE",
  ADD_TYPE: "ADD_TYPE",
  UPDATE_TYPE: "UPDATE_TYPE",
  DELETE_TYPE: "DELETE_TYPE"
}